/*
 * Generated by asn1c-f4f45aa-dirty-2025-11-24 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "V2X"
 * 	found in "C2X.asn"
 * 	`asn1c -S /home/runner/work/asn1c/asn1c/skeletons -fall-defs-global -fcompound-names -fincludes-quoted -fline-refs -fwide-types -pdu=EndApplicationMessage`
 */

#include "EndApplicationMessage.h"

static const OBJECT_IDENTIFIER_t asn_VAL_1__1_0_15784_1_0_1_ = { (uint8_t[]){ 40, 251, 40, 1, 0, 1}, 6 }; /* {1 0 15784 1 0 1} */
static const OBJECT_IDENTIFIER_t asn_VAL_2__1_0_15784_1_0_2_ = { (uint8_t[]){ 40, 251, 40, 1, 0, 2}, 6 }; /* {1 0 15784 1 0 2} */
extern asn_TYPE_descriptor_t asn_DEF_SEQUENCE_OF_CommTxPDU_1;
extern asn_TYPE_descriptor_t asn_DEF_SEQUENCE_OF_CommRxPDU_2;

static const asn_ioc_cell_t asn_IOS_Message_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_OBJECT_IDENTIFIER, &asn_VAL_1__1_0_15784_1_0_1_ },
	{ "&MessageBody", aioc__type, &asn_DEF_SEQUENCE_OF_CommTxPDU_1 },
	{ "&id", aioc__value, &asn_DEF_OBJECT_IDENTIFIER, &asn_VAL_2__1_0_15784_1_0_2_ },
	{ "&MessageBody", aioc__type, &asn_DEF_SEQUENCE_OF_CommRxPDU_2 }
};
static const asn_ioc_set_t asn_IOS_Message_1[] = {
	{ 2, 2, asn_IOS_Message_1_rows }
};
static int
memb_endApplication_Message_id_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_type_selector_result_t
select_EndApplicationMessage_endApplication_Message_msg_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_Message_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &MessageBody */
	size_t row, presence_index = 0;
	const OBJECT_IDENTIFIER_t *constraining_value = (const OBJECT_IDENTIFIER_t *)((const char *)parent_sptr + offsetof(struct EndApplicationMessage, endApplication_Message_id));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_endApplication_Message_msg_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_endApplication_Message_id_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_endApplication_Message_id_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_endApplication_Message_msg_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_endApplication_Message_msg_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_SEQUENCE_OF_CommTxPDU_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CommTxPDU,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_SEQUENCE_OF_CommTxPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_SEQUENCE_OF_CommTxPDU_specs_1 = {
	sizeof(struct EndApplicationMessage__endApplication_Message_msg__SEQUENCE_OF_CommTxPDU),
	offsetof(struct EndApplicationMessage__endApplication_Message_msg__SEQUENCE_OF_CommTxPDU, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_SEQUENCE_OF_CommTxPDU_1 = {
	"SEQUENCE OF CommTxPDU",
	"SEQUENCE OF CommTxPDU",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_SEQUENCE_OF_CommTxPDU_tags_1,
	sizeof(asn_DEF_SEQUENCE_OF_CommTxPDU_tags_1)
		/sizeof(asn_DEF_SEQUENCE_OF_CommTxPDU_tags_1[0]), /* 1 */
	asn_DEF_SEQUENCE_OF_CommTxPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_SEQUENCE_OF_CommTxPDU_tags_1)
		/sizeof(asn_DEF_SEQUENCE_OF_CommTxPDU_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_SEQUENCE_OF_CommTxPDU_1,
	1,	/* Single element */
	&asn_SPC_SEQUENCE_OF_CommTxPDU_specs_1	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SEQUENCE_OF_CommRxPDU_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CommRxPDU,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_SEQUENCE_OF_CommRxPDU_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_SEQUENCE_OF_CommRxPDU_specs_2 = {
	sizeof(struct EndApplicationMessage__endApplication_Message_msg__SEQUENCE_OF_CommRxPDU),
	offsetof(struct EndApplicationMessage__endApplication_Message_msg__SEQUENCE_OF_CommRxPDU, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_SEQUENCE_OF_CommRxPDU_2 = {
	"SEQUENCE OF CommRxPDU",
	"SEQUENCE OF CommRxPDU",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_SEQUENCE_OF_CommRxPDU_tags_2,
	sizeof(asn_DEF_SEQUENCE_OF_CommRxPDU_tags_2)
		/sizeof(asn_DEF_SEQUENCE_OF_CommRxPDU_tags_2[0]), /* 1 */
	asn_DEF_SEQUENCE_OF_CommRxPDU_tags_2,	/* Same as above */
	sizeof(asn_DEF_SEQUENCE_OF_CommRxPDU_tags_2)
		/sizeof(asn_DEF_SEQUENCE_OF_CommRxPDU_tags_2[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_SEQUENCE_OF_CommRxPDU_2,
	1,	/* Single element */
	&asn_SPC_SEQUENCE_OF_CommRxPDU_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_endApplication_Message_msg_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EndApplicationMessage__endApplication_Message_msg, choice.SEQUENCE_OF_CommTxPDU),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SEQUENCE_OF_CommTxPDU_1,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"SEQUENCE OF CommTxPDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EndApplicationMessage__endApplication_Message_msg, choice.SEQUENCE_OF_CommRxPDU),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SEQUENCE_OF_CommRxPDU_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"SEQUENCE OF CommRxPDU"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_endApplication_Message_msg_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* SEQUENCE OF CommTxPDUat 14 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 0 } /* SEQUENCE OF CommRxPDUat 14 */
};
static asn_CHOICE_specifics_t asn_SPC_endApplication_Message_msg_specs_3 = {
	sizeof(struct EndApplicationMessage__endApplication_Message_msg),
	offsetof(struct EndApplicationMessage__endApplication_Message_msg, _asn_ctx),
	offsetof(struct EndApplicationMessage__endApplication_Message_msg, present),
	sizeof(((struct EndApplicationMessage__endApplication_Message_msg *)0)->present),
	asn_MAP_endApplication_Message_msg_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_endApplication_Message_msg_3 = {
	"endApplication-Message-msg",
	"endApplication-Message-msg",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		OPEN_TYPE_constraint
	},
	asn_MBR_endApplication_Message_msg_3,
	2,	/* Elements count */
	&asn_SPC_endApplication_Message_msg_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_EndApplicationMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EndApplicationMessage, endApplication_Message_id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_endApplication_Message_id_constr_2,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_endApplication_Message_id_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_endApplication_Message_id_constraint_1
		},
		0, 0, /* No default value */
		"endApplication-Message-id"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct EndApplicationMessage, endApplication_Message_msg),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_endApplication_Message_msg_3,
		select_EndApplicationMessage_endApplication_Message_msg_type,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_endApplication_Message_msg_constr_3,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_endApplication_Message_msg_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_endApplication_Message_msg_constraint_1
		},
		0, 0, /* No default value */
		"endApplication-Message-msg"
		},
};
static const ber_tlv_tag_t asn_DEF_EndApplicationMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EndApplicationMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* endApplication-Message-idat 20 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* endApplication-Message-msgat 21 */
};
static asn_SEQUENCE_specifics_t asn_SPC_EndApplicationMessage_specs_1 = {
	sizeof(struct EndApplicationMessage),
	offsetof(struct EndApplicationMessage, _asn_ctx),
	asn_MAP_EndApplicationMessage_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EndApplicationMessage = {
	"EndApplicationMessage",
	"EndApplicationMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_EndApplicationMessage_tags_1,
	sizeof(asn_DEF_EndApplicationMessage_tags_1)
		/sizeof(asn_DEF_EndApplicationMessage_tags_1[0]), /* 1 */
	asn_DEF_EndApplicationMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_EndApplicationMessage_tags_1)
		/sizeof(asn_DEF_EndApplicationMessage_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_EndApplicationMessage_1,
	2,	/* Elements count */
	&asn_SPC_EndApplicationMessage_specs_1	/* Additional specs */
};

