/*
 * Generated by asn1c-59a85d9-dirty-2025-11-24 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "V2X"
 * 	found in "C2X.asn"
 * 	`asn1c -fall-defs-global -fcompound-names -fincludes-quoted -fline-refs -fwide-types -pdu=EndApplicationMessage`
 */

#ifndef	_EndApplicationMessage_H_
#define	_EndApplicationMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OBJECT_IDENTIFIER.h"
#include "ANY.h"
#include "asn_ioc.h"
#include "constr_SEQUENCE_OF.h"
#include "OPEN_TYPE.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EndApplicationMessage__endApplication_Message_msg_PR {
	EndApplicationMessage__endApplication_Message_msg_PR_NOTHING,	/* No components present */
	EndApplicationMessage__endApplication_Message_msg_PR_SEQUENCE_OF_CommTxPDU,
	EndApplicationMessage__endApplication_Message_msg_PR_SEQUENCE_OF_CommRxPDU
} EndApplicationMessage__endApplication_Message_msg_PR;

/* Forward declarations */
struct CommTxPDU;
struct CommRxPDU;

/* EndApplicationMessage */
typedef struct EndApplicationMessage {
	OBJECT_IDENTIFIER_t	 endApplication_Message_id;
	struct EndApplicationMessage__endApplication_Message_msg {
		EndApplicationMessage__endApplication_Message_msg_PR present;
		union EndApplicationMessage__endApplication_Message_msg_u {
			struct EndApplicationMessage__endApplication_Message_msg__SEQUENCE_OF_CommTxPDU {
				A_SEQUENCE_OF(struct CommTxPDU) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} SEQUENCE_OF_CommTxPDU;
			struct EndApplicationMessage__endApplication_Message_msg__SEQUENCE_OF_CommRxPDU {
				A_SEQUENCE_OF(struct CommRxPDU) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} SEQUENCE_OF_CommRxPDU;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} endApplication_Message_msg;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EndApplicationMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EndApplicationMessage;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CommTxPDU.h"
#include "CommRxPDU.h"

#endif	/* _EndApplicationMessage_H_ */
#include "asn_internal.h"
