/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestChoiceExtensionGroupsNoComma"
 * 	found in "tests/tests-asn1c-compiler/166-choice-extension-groups-no-comma-OK.asn1"
 */

#ifndef	_ChoiceMixed_H_
#define	_ChoiceMixed_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChoiceMixed_PR {
	ChoiceMixed_PR_NOTHING,	/* No components present */
	ChoiceMixed_PR_base,
	/* Extensions may appear below */
	ChoiceMixed_PR_extElement,
	ChoiceMixed_PR_extGroup1,
	ChoiceMixed_PR_extGroup2
} ChoiceMixed_PR;

/* ChoiceMixed */
typedef struct ChoiceMixed {
	ChoiceMixed_PR present;
	union ChoiceMixed_u {
		long	 base;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		long	 extElement;
		long	 extGroup1;
		BOOLEAN_t	 extGroup2;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChoiceMixed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChoiceMixed;

#ifdef __cplusplus
}
#endif

#endif	/* _ChoiceMixed_H_ */
#include <asn_internal.h>
