/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestExtensibleChoice"
 * 	found in "tests/tests-asn1c-compiler/165-choice-extended-group-OK.asn1"
 */

#ifndef	_Choice_H_
#define	_Choice_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Choice_PR {
	Choice_PR_NOTHING,	/* No components present */
	Choice_PR_a,
	/* Extensions may appear below */
	Choice_PR_b,
	Choice_PR_c,
	Choice_PR_d,
	Choice_PR_e,
	Choice_PR_f,
	Choice_PR_g
} Choice_PR;

/* Choice */
typedef struct Choice {
	Choice_PR present;
	union Choice_u {
		long	 a;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		long	 b;
		long	 c;
		long	 d;
		long	 e;
		long	 f;
		long	 g;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Choice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Choice;

#ifdef __cplusplus
}
#endif

#endif	/* _Choice_H_ */
#include <asn_internal.h>
