/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestChoiceExtensionGroupsNoComma"
 * 	found in "tests/tests-asn1c-compiler/166-choice-extension-groups-no-comma-OK.asn1"
 */

#ifndef	_ChoiceWithExtensionGroup_H_
#define	_ChoiceWithExtensionGroup_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChoiceWithExtensionGroup_PR {
	ChoiceWithExtensionGroup_PR_NOTHING,	/* No components present */
	ChoiceWithExtensionGroup_PR_base,
	/* Extensions may appear below */
	ChoiceWithExtensionGroup_PR_ext1,
	ChoiceWithExtensionGroup_PR_ext2
} ChoiceWithExtensionGroup_PR;

/* ChoiceWithExtensionGroup */
typedef struct ChoiceWithExtensionGroup {
	ChoiceWithExtensionGroup_PR present;
	union ChoiceWithExtensionGroup_u {
		long	 base;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		long	 ext1;
		BOOLEAN_t	 ext2;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChoiceWithExtensionGroup_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChoiceWithExtensionGroup;

#ifdef __cplusplus
}
#endif

#endif	/* _ChoiceWithExtensionGroup_H_ */
#include <asn_internal.h>
