/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Test-Module2"
 * 	found in "/tmp/test_complex_extension.asn1"
 */

#ifndef	_ImmediateExtension_H_
#define	_ImmediateExtension_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ImmediateExtension_PR {
	ImmediateExtension_PR_NOTHING,	/* No components present */
	ImmediateExtension_PR_base,
	/* Extensions may appear below */
	ImmediateExtension_PR_ext1,
	ImmediateExtension_PR_ext2
} ImmediateExtension_PR;

/* ImmediateExtension */
typedef struct ImmediateExtension {
	ImmediateExtension_PR present;
	union ImmediateExtension_u {
		long	 base;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		long	 ext1;
		BOOLEAN_t	 ext2;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ImmediateExtension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ImmediateExtension;

#ifdef __cplusplus
}
#endif

#endif	/* _ImmediateExtension_H_ */
#include <asn_internal.h>
