/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Test-Module2"
 * 	found in "/tmp/test_complex_extension.asn1"
 */

#ifndef	_MultipleGroups_H_
#define	_MultipleGroups_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <OCTET_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MultipleGroups_PR {
	MultipleGroups_PR_NOTHING,	/* No components present */
	MultipleGroups_PR_a,
	/* Extensions may appear below */
	MultipleGroups_PR_b,
	MultipleGroups_PR_c,
	MultipleGroups_PR_d,
	MultipleGroups_PR_e,
	MultipleGroups_PR_f,
	MultipleGroups_PR_g
} MultipleGroups_PR;

/* MultipleGroups */
typedef struct MultipleGroups {
	MultipleGroups_PR present;
	union MultipleGroups_u {
		long	 a;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		long	 b;
		long	 c;
		long	 d;
		BOOLEAN_t	 e;
		long	 f;
		OCTET_STRING_t	 g;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MultipleGroups_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MultipleGroups;

#ifdef __cplusplus
}
#endif

#endif	/* _MultipleGroups_H_ */
#include <asn_internal.h>
