/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Test-Module2"
 * 	found in "/tmp/test_complex_extension.asn1"
 */

#ifndef	_NestedChoice_H_
#define	_NestedChoice_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_CHOICE.h>
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NestedChoice_PR {
	NestedChoice_PR_NOTHING,	/* No components present */
	NestedChoice_PR_option1,
	NestedChoice_PR_option2,
	/* Extensions may appear below */
	NestedChoice_PR_option3
} NestedChoice_PR;
typedef enum option1_PR {
	option1_PR_NOTHING,	/* No components present */
	option1_PR_a,
	/* Extensions may appear below */
	option1_PR_b,
	option1_PR_c
} option1_PR;
typedef enum option3_PR {
	option3_PR_NOTHING,	/* No components present */
	option3_PR_x,
	option3_PR_y
} option3_PR;

/* NestedChoice */
typedef struct NestedChoice {
	NestedChoice_PR present;
	union NestedChoice_u {
		struct option1 {
			option1_PR present;
			union NestedChoice__option1_u {
				long	 a;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				long	 b;
				OCTET_STRING_t	 c;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} option1;
		long	 option2;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		struct option3 {
			option3_PR present;
			union NestedChoice__option3_u {
				long	 x;
				BOOLEAN_t	 y;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} option3;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NestedChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NestedChoice;

#ifdef __cplusplus
}
#endif

#endif	/* _NestedChoice_H_ */
#include <asn_internal.h>
