/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Test-Module3"
 * 	found in "/tmp/test_parse_error.asn1"
 */

#ifndef	_ProblematicChoice_H_
#define	_ProblematicChoice_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProblematicChoice_PR {
	ProblematicChoice_PR_NOTHING,	/* No components present */
	ProblematicChoice_PR_a,
	/* Extensions may appear below */
	ProblematicChoice_PR_b
} ProblematicChoice_PR;

/* ProblematicChoice */
typedef struct ProblematicChoice {
	ProblematicChoice_PR present;
	union ProblematicChoice_u {
		long	 a;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		long	 b;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProblematicChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProblematicChoice;

#ifdef __cplusplus
}
#endif

#endif	/* _ProblematicChoice_H_ */
#include <asn_internal.h>
