/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Test-Module3"
 * 	found in "/tmp/test_parse_error.asn1"
 */

#ifndef	_ProblematicChoice2_H_
#define	_ProblematicChoice2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProblematicChoice2_PR {
	ProblematicChoice2_PR_NOTHING,	/* No components present */
	ProblematicChoice2_PR_a,
	/* Extensions may appear below */
	ProblematicChoice2_PR_b,
	ProblematicChoice2_PR_c
} ProblematicChoice2_PR;

/* ProblematicChoice2 */
typedef struct ProblematicChoice2 {
	ProblematicChoice2_PR present;
	union ProblematicChoice2_u {
		long	 a;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		long	 b;
		long	 c;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProblematicChoice2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProblematicChoice2;

#ifdef __cplusplus
}
#endif

#endif	/* _ProblematicChoice2_H_ */
#include <asn_internal.h>
