/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TestOctetConstraint"
 * 	found in "test_f1ap_issue.asn1"
 */

#ifndef	_TestMessage_H_
#define	_TestMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <ANY.h>
#include <asn_ioc.h>
#include <OCTET_STRING.h>
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum extensionValue_PR {
	extensionValue_PR_NOTHING,	/* No components present */
	extensionValue_PR_OCTET_STRING_SIZE_3_
} extensionValue_PR;

/* TestMessage */
typedef struct TestMessage {
	long	 extensionID;
	struct extensionValue {
		extensionValue_PR present;
		union TestMessage__extensionValue_u {
			OCTET_STRING_t	 OCTET_STRING_SIZE_3_;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TestMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _TestMessage_H_ */
#include <asn_internal.h>
