/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SimpleConstraint"
 * 	found in "./test_simple_constraint.asn1"
 */

#ifndef	_TestMessage_H_
#define	_TestMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TestMessage */
typedef struct TestMessage {
	OCTET_STRING_t	 constrainedOctet;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TestMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _TestMessage_H_ */
#include <asn_internal.h>
