/*
 * Generated by asn1c-e1bf5d4-dirty-2025-11-21 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "ModuleTestXERDecoding"
 * 	found in "/home/runner/work/asn1c/asn1c/tests/tests-asn1c-compiler/70-xer-test-OK.asn1"
 * 	`asn1c -S /home/runner/work/asn1c/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_NamedSetOfEnums_H_
#define	_NamedSetOfEnums_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum name {
	name_one	= 0,
	name_oneMore	= 1
} e_name;

/* NamedSetOfEnums */
typedef long	 name_t;
typedef struct NamedSetOfEnums {
	A_SET_OF(long) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NamedSetOfEnums_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_name;
asn_struct_free_f name_free;
asn_struct_print_f name_print;
asn_constr_check_f name_constraint;
ber_type_decoder_f name_decode_ber;
der_type_encoder_f name_encode_der;
xer_type_decoder_f name_decode_xer;
xer_type_encoder_f name_encode_xer;
jer_type_encoder_f name_encode_jer;
oer_type_decoder_f name_decode_oer;
oer_type_encoder_f name_encode_oer;
per_type_decoder_f name_decode_uper;
per_type_encoder_f name_encode_uper;
per_type_decoder_f name_decode_aper;
per_type_encoder_f name_encode_aper;
extern asn_TYPE_descriptor_t asn_DEF_NamedSetOfEnums;
extern asn_SET_OF_specifics_t asn_SPC_NamedSetOfEnums_specs_1;
extern asn_TYPE_member_t asn_MBR_NamedSetOfEnums_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _NamedSetOfEnums_H_ */
#include <asn_internal.h>
