/*
 * Generated by asn1c-e1bf5d4-dirty-2025-11-21 (https://github.com/mouse07410/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_PDU;
extern struct asn_TYPE_descriptor_s asn_DEF_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module ModuleTestXERDecoding in /home/runner/work/asn1c/asn1c/tests/tests-asn1c-compiler/70-xer-test-OK.asn1 */
	&asn_DEF_PDU,	
	/* From module ASN1C-UsefulInformationObjectClasses in /home/runner/work/asn1c/asn1c/skeletons/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_EXTERNAL,	
	0
};

