/*
 * Generated by asn1c-e1bf5d4-dirty-2025-11-21 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "ModuleTestXERDecoding"
 * 	found in "/home/runner/work/asn1c/asn1c/tests/tests-asn1c-compiler/70-xer-test-OK.asn1"
 * 	`asn1c -S /home/runner/work/asn1c/asn1c/skeletons -flink-skeletons -Wdebug-compiler`
 */

#ifndef	_Sequence_H_
#define	_Sequence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Sequence;

/* Sequence */
typedef struct Sequence {
	long	 integer;
	struct Sequence	*sequence;	/* OPTIONAL */
	BIT_STRING_t	*bits;	/* OPTIONAL */
	UTF8String_t	 string;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Sequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Sequence;
extern asn_SEQUENCE_specifics_t asn_SPC_Sequence_specs_1;
extern asn_TYPE_member_t asn_MBR_Sequence_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Sequence.h"

#endif	/* _Sequence_H_ */
#include <asn_internal.h>
