/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_ATMParameters_H_
#define	_ATMParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NULL.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ATMParameters */
typedef struct ATMParameters {
	long	 maxNTUSize;
	NULL_t	*atmUBR;	/* OPTIONAL */
	NULL_t	*atmrtVBR;	/* OPTIONAL */
	NULL_t	*atmABR;	/* OPTIONAL */
	NULL_t	*atmCBR;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ATMParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ATMParameters;
extern asn_SEQUENCE_specifics_t asn_SPC_ATMParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_ATMParameters_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _ATMParameters_H_ */
#include <asn_internal.h>
