/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_CallCapacity_H_
#define	_CallCapacity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CallCapacityInfo;

/* CallCapacity */
typedef struct CallCapacity {
	struct CallCapacityInfo	*maximumCallCapacity;	/* OPTIONAL */
	struct CallCapacityInfo	*currentCallCapacity;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CallCapacity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallCapacity;
extern asn_SEQUENCE_specifics_t asn_SPC_CallCapacity_specs_1;
extern asn_TYPE_member_t asn_MBR_CallCapacity_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CallCapacityInfo.h"

#endif	/* _CallCapacity_H_ */
#include <asn_internal.h>
