/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_CallType_H_
#define	_CallType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CallType {
	CallType_pointToPoint	= 0,
	CallType_oneToN	= 1,
	CallType_nToOne	= 2,
	CallType_nToN	= 3
} e_CallType;

/* CallType */
typedef long	 CallType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CallType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CallType;
extern const asn_INTEGER_specifics_t asn_SPC_CallType_specs_1;
asn_struct_free_f CallType_free;
asn_struct_print_f CallType_print;
asn_constr_check_f CallType_constraint;
ber_type_decoder_f CallType_decode_ber;
der_type_encoder_f CallType_encode_der;
xer_type_decoder_f CallType_decode_xer;
xer_type_encoder_f CallType_encode_xer;
jer_type_encoder_f CallType_encode_jer;
oer_type_decoder_f CallType_decode_oer;
oer_type_encoder_f CallType_encode_oer;
per_type_decoder_f CallType_decode_uper;
per_type_encoder_f CallType_encode_uper;
per_type_decoder_f CallType_decode_aper;
per_type_encoder_f CallType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CallType_H_ */
#include <asn_internal.h>
