/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_CallModel_H_
#define	_CallModel_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CallModel {
	CallModel_direct	= 0,
	CallModel_gatekeeperRouted	= 1
} e_CallModel;

/* CallModel */
typedef long	 CallModel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallModel;
asn_struct_free_f CallModel_free;
asn_struct_print_f CallModel_print;
asn_constr_check_f CallModel_constraint;
ber_type_decoder_f CallModel_decode_ber;
der_type_encoder_f CallModel_encode_der;
xer_type_decoder_f CallModel_decode_xer;
xer_type_encoder_f CallModel_encode_xer;
jer_type_encoder_f CallModel_encode_jer;
oer_type_decoder_f CallModel_decode_oer;
oer_type_encoder_f CallModel_encode_oer;
per_type_decoder_f CallModel_decode_uper;
per_type_encoder_f CallModel_encode_uper;
per_type_decoder_f CallModel_decode_aper;
per_type_encoder_f CallModel_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CallModel_H_ */
#include <asn_internal.h>
