/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_CertificateCapability_H_
#define	_CertificateCapability_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NonStandardParameter;
struct X509Capability;

/* CertificateCapability */
typedef struct CertificateCapability {
	struct NonStandardParameter	*nonStandard;	/* OPTIONAL */
	struct X509Capability	*x509Capability;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertificateCapability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificateCapability;
extern asn_SEQUENCE_specifics_t asn_SPC_CertificateCapability_specs_1;
extern asn_TYPE_member_t asn_MBR_CertificateCapability_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NonStandardParameter.h"
#include "X509Capability.h"

#endif	/* _CertificateCapability_H_ */
#include <asn_internal.h>
