/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_ChallengeString_H_
#define	_ChallengeString_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ChallengeString */
typedef OCTET_STRING_t	 ChallengeString_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ChallengeString_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ChallengeString;
asn_struct_free_f ChallengeString_free;
asn_struct_print_f ChallengeString_print;
asn_constr_check_f ChallengeString_constraint;
ber_type_decoder_f ChallengeString_decode_ber;
der_type_encoder_f ChallengeString_encode_der;
xer_type_decoder_f ChallengeString_decode_xer;
xer_type_encoder_f ChallengeString_encode_xer;
jer_type_encoder_f ChallengeString_encode_jer;
oer_type_decoder_f ChallengeString_decode_oer;
oer_type_encoder_f ChallengeString_encode_oer;
per_type_decoder_f ChallengeString_decode_uper;
per_type_encoder_f ChallengeString_encode_uper;
per_type_decoder_f ChallengeString_decode_aper;
per_type_encoder_f ChallengeString_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ChallengeString_H_ */
#include <asn_internal.h>
