/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_CircuitInfo_H_
#define	_CircuitInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CircuitIdentifier;
struct GenericData;

/* CircuitInfo */
typedef struct CircuitInfo {
	struct CircuitIdentifier	*sourceCircuitID;	/* OPTIONAL */
	struct CircuitIdentifier	*destinationCircuitID;	/* OPTIONAL */
	struct CircuitInfo__genericData {
		A_SEQUENCE_OF(struct GenericData) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *genericData;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CircuitInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CircuitInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_CircuitInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_CircuitInfo_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CircuitIdentifier.h"
#include "GenericData.h"

#endif	/* _CircuitInfo_H_ */
#include <asn_internal.h>
