/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_ClearToken_H_
#define	_ClearToken_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include "TimeStamp.h"
#include "Password.h"
#include "ChallengeString.h"
#include "RandomVal.h"
#include "Identifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DHset;
struct TypedCertificate;
struct NonStandardParameter;

/* ClearToken */
typedef struct ClearToken {
	OBJECT_IDENTIFIER_t	 tokenOID;
	TimeStamp_t	*timeStamp;	/* OPTIONAL */
	Password_t	*password;	/* OPTIONAL */
	struct DHset	*dhkey;	/* OPTIONAL */
	ChallengeString_t	*challenge;	/* OPTIONAL */
	RandomVal_t	*random;	/* OPTIONAL */
	struct TypedCertificate	*certificate;	/* OPTIONAL */
	Identifier_t	*generalID;	/* OPTIONAL */
	struct NonStandardParameter	*nonStandard;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ClearToken_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ClearToken;
extern asn_SEQUENCE_specifics_t asn_SPC_ClearToken_specs_1;
extern asn_TYPE_member_t asn_MBR_ClearToken_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DHset.h"
#include "TypedCertificate.h"
#include "NonStandardParameter.h"

#endif	/* _ClearToken_H_ */
#include <asn_internal.h>
