/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_ConferenceGoal_H_
#define	_ConferenceGoal_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConferenceGoal_PR {
	ConferenceGoal_PR_NOTHING,	/* No components present */
	ConferenceGoal_PR_create,
	ConferenceGoal_PR_join,
	ConferenceGoal_PR_invite
	/* Extensions may appear below */
	
} ConferenceGoal_PR;

/* ConferenceGoal */
typedef struct ConferenceGoal {
	ConferenceGoal_PR present;
	union ConferenceGoal_u {
		NULL_t	 create;
		NULL_t	 join;
		NULL_t	 invite;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConferenceGoal_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConferenceGoal;
extern asn_CHOICE_specifics_t asn_SPC_ConferenceGoal_specs_1;
extern asn_TYPE_member_t asn_MBR_ConferenceGoal_1[3];
extern asn_per_constraints_t asn_PER_type_ConferenceGoal_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ConferenceGoal_H_ */
#include <asn_internal.h>
