/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_ConferenceIdentifier_H_
#define	_ConferenceIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ConferenceIdentifier */
typedef OCTET_STRING_t	 ConferenceIdentifier_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ConferenceIdentifier_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ConferenceIdentifier;
asn_struct_free_f ConferenceIdentifier_free;
asn_struct_print_f ConferenceIdentifier_print;
asn_constr_check_f ConferenceIdentifier_constraint;
ber_type_decoder_f ConferenceIdentifier_decode_ber;
der_type_encoder_f ConferenceIdentifier_encode_der;
xer_type_decoder_f ConferenceIdentifier_decode_xer;
xer_type_encoder_f ConferenceIdentifier_encode_xer;
jer_type_encoder_f ConferenceIdentifier_encode_jer;
oer_type_decoder_f ConferenceIdentifier_decode_oer;
oer_type_encoder_f ConferenceIdentifier_encode_oer;
per_type_decoder_f ConferenceIdentifier_decode_uper;
per_type_encoder_f ConferenceIdentifier_encode_uper;
per_type_decoder_f ConferenceIdentifier_decode_aper;
per_type_encoder_f ConferenceIdentifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ConferenceIdentifier_H_ */
#include <asn_internal.h>
