/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_ConnectionParameters_H_
#define	_ConnectionParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct QOSCapabilities;

/* ConnectionParameters */
typedef struct ConnectionParameters {
	struct QOSCapabilities	*qosCapabilities;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConnectionParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConnectionParameters;
extern asn_SEQUENCE_specifics_t asn_SPC_ConnectionParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_ConnectionParameters_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "QOSCapabilities.h"

#endif	/* _ConnectionParameters_H_ */
#include <asn_internal.h>
