/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_Contents_H_
#define	_Contents_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <IA5String.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Contents_PR {
	Contents_PR_NOTHING,	/* No components present */
	Contents_PR_raw,
	Contents_PR_text
	/* Extensions may appear below */
	
} Contents_PR;

/* Contents */
typedef struct Contents {
	Contents_PR present;
	union Contents_u {
		OCTET_STRING_t	 raw;
		IA5String_t	 text;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Contents_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Contents;
extern asn_CHOICE_specifics_t asn_SPC_Contents_specs_1;
extern asn_TYPE_member_t asn_MBR_Contents_1[2];
extern asn_per_constraints_t asn_PER_type_Contents_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Contents_H_ */
#include <asn_internal.h>
