/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_Content_H_
#define	_Content_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <IA5String.h>
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Content_PR {
	Content_PR_NOTHING,	/* No components present */
	Content_PR_raw,
	Content_PR_text,
	Content_PR_number,
	Content_PR_compound,
	Content_PR_nested
	/* Extensions may appear below */
	
} Content_PR;

/* Forward declarations */
struct EnumeratedParameter;
struct GenericData;

/* Content */
typedef struct Content {
	Content_PR present;
	union Content_u {
		OCTET_STRING_t	 raw;
		IA5String_t	 text;
		long	 number;
		struct Content__compound {
			A_SEQUENCE_OF(struct EnumeratedParameter) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} compound;
		struct Content__nested {
			A_SEQUENCE_OF(struct GenericData) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} nested;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Content_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Content;
extern asn_CHOICE_specifics_t asn_SPC_Content_specs_1;
extern asn_TYPE_member_t asn_MBR_Content_1[5];
extern asn_per_constraints_t asn_PER_type_Content_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EnumeratedParameter.h"
#include "GenericData.h"

#endif	/* _Content_H_ */
#include <asn_internal.h>
