/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_CryptoGKCert_H_
#define	_CryptoGKCert_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EncodedCertificate.h"
#include <OBJECT_IDENTIFIER.h>
#include "Params.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CryptoGKCert */
typedef struct CryptoGKCert {
	EncodedCertificate_t	 toBeSigned;
	OBJECT_IDENTIFIER_t	 algorithmOID;
	Params_t	 paramS;
	BIT_STRING_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CryptoGKCert_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CryptoGKCert;
extern asn_SEQUENCE_specifics_t asn_SPC_CryptoGKCert_specs_1;
extern asn_TYPE_member_t asn_MBR_CryptoGKCert_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _CryptoGKCert_H_ */
#include <asn_internal.h>
