/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_CryptoGKPwdEncr_H_
#define	_CryptoGKPwdEncr_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GatekeeperIdentifier.h"
#include "TimeStamp.h"
#include "ENCRYPTED.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CryptoGKPwdEncr */
typedef struct CryptoGKPwdEncr {
	GatekeeperIdentifier_t	 gatekeeperId;
	TimeStamp_t	 timeStamp;
	ENCRYPTED_t	 token;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CryptoGKPwdEncr_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CryptoGKPwdEncr;
extern asn_SEQUENCE_specifics_t asn_SPC_CryptoGKPwdEncr_specs_1;
extern asn_TYPE_member_t asn_MBR_CryptoGKPwdEncr_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _CryptoGKPwdEncr_H_ */
#include <asn_internal.h>
