/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_CryptoH323Token_H_
#define	_CryptoH323Token_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CryptoEPPwdHash.h"
#include "CryptoGKPwdHash.h"
#include "CryptoEPPwdEncr.h"
#include "CryptoGKPwdEncr.h"
#include "CryptoEPCert.h"
#include "CryptoGKCert.h"
#include "CryptoFastStart.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CryptoH323Token_PR {
	CryptoH323Token_PR_NOTHING,	/* No components present */
	CryptoH323Token_PR_cryptoEPPwdHash,
	CryptoH323Token_PR_cryptoGKPwdHash,
	CryptoH323Token_PR_cryptoEPPwdEncr,
	CryptoH323Token_PR_cryptoGKPwdEncr,
	CryptoH323Token_PR_cryptoEPCert,
	CryptoH323Token_PR_cryptoGKCert,
	CryptoH323Token_PR_cryptoFastStart,
	CryptoH323Token_PR_nestedcryptoToken
	/* Extensions may appear below */
	
} CryptoH323Token_PR;

/* Forward declarations */
struct NestedcryptoToken;

/* CryptoH323Token */
typedef struct CryptoH323Token {
	CryptoH323Token_PR present;
	union CryptoH323Token_u {
		CryptoEPPwdHash_t	 cryptoEPPwdHash;
		CryptoGKPwdHash_t	 cryptoGKPwdHash;
		CryptoEPPwdEncr_t	 cryptoEPPwdEncr;
		CryptoGKPwdEncr_t	 cryptoGKPwdEncr;
		CryptoEPCert_t	 cryptoEPCert;
		CryptoGKCert_t	 cryptoGKCert;
		CryptoFastStart_t	 cryptoFastStart;
		struct NestedcryptoToken	*nestedcryptoToken;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CryptoH323Token_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CryptoH323Token;
extern asn_CHOICE_specifics_t asn_SPC_CryptoH323Token_specs_1;
extern asn_TYPE_member_t asn_MBR_CryptoH323Token_1[8];
extern asn_per_constraints_t asn_PER_type_CryptoH323Token_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NestedcryptoToken.h"

#endif	/* _CryptoH323Token_H_ */
#include <asn_internal.h>
