/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_CryptoEPPwdHash_H_
#define	_CryptoEPPwdHash_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AliasAddress.h"
#include "TimeStamp.h"
#include "HASHED.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CryptoEPPwdHash */
typedef struct CryptoEPPwdHash {
	AliasAddress_t	 alias;
	TimeStamp_t	 timeStamp;
	HASHED_t	 token;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CryptoEPPwdHash_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CryptoEPPwdHash;
extern asn_SEQUENCE_specifics_t asn_SPC_CryptoEPPwdHash_specs_1;
extern asn_TYPE_member_t asn_MBR_CryptoEPPwdHash_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _CryptoEPPwdHash_H_ */
#include <asn_internal.h>
