/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_DataPartyNumber_H_
#define	_DataPartyNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DataTypeOfNumber.h"
#include "NumberDigits.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DataPartyNumber */
typedef struct DataPartyNumber {
	DataTypeOfNumber_t	 dataTypeOfNumber;
	NumberDigits_t	 dataNumberDigits;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataPartyNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataPartyNumber;
extern asn_SEQUENCE_specifics_t asn_SPC_DataPartyNumber_specs_1;
extern asn_TYPE_member_t asn_MBR_DataPartyNumber_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _DataPartyNumber_H_ */
#include <asn_internal.h>
