/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_DataTypeOfNumber_H_
#define	_DataTypeOfNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DataTypeOfNumber {
	DataTypeOfNumber_unknown	= 0,
	DataTypeOfNumber_internationalNumber	= 1,
	DataTypeOfNumber_nationalNumber	= 2,
	DataTypeOfNumber_networkSpecificNumber	= 3,
	DataTypeOfNumber_subscriberNumber	= 4,
	DataTypeOfNumber_abbreviatedNumber	= 6
	/*
	 * Enumeration is extensible
	 */
} e_DataTypeOfNumber;

/* DataTypeOfNumber */
typedef long	 DataTypeOfNumber_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DataTypeOfNumber_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DataTypeOfNumber;
extern const asn_INTEGER_specifics_t asn_SPC_DataTypeOfNumber_specs_1;
asn_struct_free_f DataTypeOfNumber_free;
asn_struct_print_f DataTypeOfNumber_print;
asn_constr_check_f DataTypeOfNumber_constraint;
ber_type_decoder_f DataTypeOfNumber_decode_ber;
der_type_encoder_f DataTypeOfNumber_encode_der;
xer_type_decoder_f DataTypeOfNumber_decode_xer;
xer_type_encoder_f DataTypeOfNumber_encode_xer;
jer_type_encoder_f DataTypeOfNumber_encode_jer;
oer_type_decoder_f DataTypeOfNumber_decode_oer;
oer_type_encoder_f DataTypeOfNumber_encode_oer;
per_type_decoder_f DataTypeOfNumber_decode_uper;
per_type_encoder_f DataTypeOfNumber_encode_uper;
per_type_decoder_f DataTypeOfNumber_decode_aper;
per_type_encoder_f DataTypeOfNumber_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _DataTypeOfNumber_H_ */
#include <asn_internal.h>
