/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#include "DataTypeOfNumber.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_DataTypeOfNumber_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_DataTypeOfNumber_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  5 }	/* (0..5,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_DataTypeOfNumber_value2enum_1[] = {
	{ 0,	7,	"unknown" },
	{ 1,	19,	"internationalNumber" },
	{ 2,	14,	"nationalNumber" },
	{ 3,	21,	"networkSpecificNumber" },
	{ 4,	16,	"subscriberNumber" },
	{ 6,	17,	"abbreviatedNumber" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_DataTypeOfNumber_enum2value_1[] = {
	5,	/* abbreviatedNumber(6) */
	1,	/* internationalNumber(1) */
	2,	/* nationalNumber(2) */
	3,	/* networkSpecificNumber(3) */
	4,	/* subscriberNumber(4) */
	0	/* unknown(0) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_DataTypeOfNumber_specs_1 = {
	asn_MAP_DataTypeOfNumber_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_DataTypeOfNumber_enum2value_1,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	7,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_DataTypeOfNumber_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_DataTypeOfNumber = {
	"DataTypeOfNumber",
	"DataTypeOfNumber",
	&asn_OP_NativeEnumerated,
	asn_DEF_DataTypeOfNumber_tags_1,
	sizeof(asn_DEF_DataTypeOfNumber_tags_1)
		/sizeof(asn_DEF_DataTypeOfNumber_tags_1[0]), /* 1 */
	asn_DEF_DataTypeOfNumber_tags_1,	/* Same as above */
	sizeof(asn_DEF_DataTypeOfNumber_tags_1)
		/sizeof(asn_DEF_DataTypeOfNumber_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_DataTypeOfNumber_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_DataTypeOfNumber_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_DataTypeOfNumber_specs_1	/* Additional specs */
};

