/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_DHset_H_
#define	_DHset_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DHset */
typedef struct DHset {
	BIT_STRING_t	 halfkey;
	BIT_STRING_t	 modSize;
	BIT_STRING_t	 generator;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DHset_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DHset;
extern asn_SEQUENCE_specifics_t asn_SPC_DHset_specs_1;
extern asn_TYPE_member_t asn_MBR_DHset_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _DHset_H_ */
#include <asn_internal.h>
