/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_DialedDigits_H_
#define	_DialedDigits_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DialedDigits */
typedef IA5String_t	 DialedDigits_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DialedDigits_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DialedDigits;
asn_struct_free_f DialedDigits_free;
asn_struct_print_f DialedDigits_print;
asn_constr_check_f DialedDigits_constraint;
ber_type_decoder_f DialedDigits_decode_ber;
der_type_encoder_f DialedDigits_encode_der;
xer_type_decoder_f DialedDigits_decode_xer;
xer_type_encoder_f DialedDigits_encode_xer;
jer_type_encoder_f DialedDigits_encode_jer;
oer_type_decoder_f DialedDigits_decode_oer;
oer_type_encoder_f DialedDigits_encode_oer;
per_type_decoder_f DialedDigits_decode_uper;
per_type_encoder_f DialedDigits_encode_uper;
per_type_decoder_f DialedDigits_decode_aper;
per_type_encoder_f DialedDigits_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _DialedDigits_H_ */
#include <asn_internal.h>
