/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_EncodedFastStart_H_
#define	_EncodedFastStart_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EncodedFastStart */
typedef OCTET_STRING_t	 EncodedFastStart_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncodedFastStart;
asn_struct_free_f EncodedFastStart_free;
asn_struct_print_f EncodedFastStart_print;
asn_constr_check_f EncodedFastStart_constraint;
ber_type_decoder_f EncodedFastStart_decode_ber;
der_type_encoder_f EncodedFastStart_encode_der;
xer_type_decoder_f EncodedFastStart_decode_xer;
xer_type_encoder_f EncodedFastStart_encode_xer;
jer_type_encoder_f EncodedFastStart_encode_jer;
oer_type_decoder_f EncodedFastStart_decode_oer;
oer_type_encoder_f EncodedFastStart_encode_oer;
per_type_decoder_f EncodedFastStart_decode_uper;
per_type_encoder_f EncodedFastStart_encode_uper;
per_type_decoder_f EncodedFastStart_decode_aper;
per_type_encoder_f EncodedFastStart_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EncodedFastStart_H_ */
#include <asn_internal.h>
