/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_EncryptionCapability_H_
#define	_EncryptionCapability_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NonStandardParameter.h"
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EncryptionCapability_PR {
	EncryptionCapability_PR_NOTHING,	/* No components present */
	EncryptionCapability_PR_nonStandard,
	EncryptionCapability_PR_des40,
	EncryptionCapability_PR_des56,
	EncryptionCapability_PR_triple_des
	/* Extensions may appear below */
	
} EncryptionCapability_PR;

/* EncryptionCapability */
typedef struct EncryptionCapability {
	EncryptionCapability_PR present;
	union EncryptionCapability_u {
		NonStandardParameter_t	 nonStandard;
		NULL_t	 des40;
		NULL_t	 des56;
		NULL_t	 triple_des;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EncryptionCapability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncryptionCapability;
extern asn_CHOICE_specifics_t asn_SPC_EncryptionCapability_specs_1;
extern asn_TYPE_member_t asn_MBR_EncryptionCapability_1[4];
extern asn_per_constraints_t asn_PER_type_EncryptionCapability_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _EncryptionCapability_H_ */
#include <asn_internal.h>
