/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_EndpointType_H_
#define	_EndpointType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NonStandardParameter;
struct VendorIdentifier;
struct GatekeeperInfo;
struct GatewayInfo;
struct McuInfo;
struct TerminalInfo;

/* EndpointType */
typedef struct EndpointType {
	struct NonStandardParameter	*nonStandardData;	/* OPTIONAL */
	struct VendorIdentifier	*vendor;	/* OPTIONAL */
	struct GatekeeperInfo	*gatekeeper;	/* OPTIONAL */
	struct GatewayInfo	*gateway;	/* OPTIONAL */
	struct McuInfo	*mcu;	/* OPTIONAL */
	struct TerminalInfo	*terminal;	/* OPTIONAL */
	BOOLEAN_t	 mc;
	BOOLEAN_t	 undefinedNode;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EndpointType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EndpointType;
extern asn_SEQUENCE_specifics_t asn_SPC_EndpointType_specs_1;
extern asn_TYPE_member_t asn_MBR_EndpointType_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NonStandardParameter.h"
#include "VendorIdentifier.h"
#include "GatekeeperInfo.h"
#include "GatewayInfo.h"
#include "McuInfo.h"
#include "TerminalInfo.h"

#endif	/* _EndpointType_H_ */
#include <asn_internal.h>
