/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_ExtendedAliasAddress_H_
#define	_ExtendedAliasAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AliasAddress.h"
#include "PresentationIndicator.h"
#include "ScreeningIndicator.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExtendedAliasAddress */
typedef struct ExtendedAliasAddress {
	AliasAddress_t	 address;
	PresentationIndicator_t	*presentationIndicator;	/* OPTIONAL */
	ScreeningIndicator_t	*screeningIndicator;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExtendedAliasAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExtendedAliasAddress;
extern asn_SEQUENCE_specifics_t asn_SPC_ExtendedAliasAddress_specs_1;
extern asn_TYPE_member_t asn_MBR_ExtendedAliasAddress_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ExtendedAliasAddress_H_ */
#include <asn_internal.h>
