/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#include "ExtendedAliasAddress.h"

asn_TYPE_member_t asn_MBR_ExtendedAliasAddress_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ExtendedAliasAddress, address),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AliasAddress,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"address"
		},
	{ ATF_POINTER, 2, offsetof(struct ExtendedAliasAddress, presentationIndicator),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PresentationIndicator,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"presentationIndicator"
		},
	{ ATF_POINTER, 1, offsetof(struct ExtendedAliasAddress, screeningIndicator),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ScreeningIndicator,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"screeningIndicator"
		},
};
static const int asn_MAP_ExtendedAliasAddress_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_ExtendedAliasAddress_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ExtendedAliasAddress_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* address */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* presentationIndicator */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* screeningIndicator */
};
asn_SEQUENCE_specifics_t asn_SPC_ExtendedAliasAddress_specs_1 = {
	sizeof(struct ExtendedAliasAddress),
	offsetof(struct ExtendedAliasAddress, _asn_ctx),
	asn_MAP_ExtendedAliasAddress_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ExtendedAliasAddress_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ExtendedAliasAddress = {
	"ExtendedAliasAddress",
	"ExtendedAliasAddress",
	&asn_OP_SEQUENCE,
	asn_DEF_ExtendedAliasAddress_tags_1,
	sizeof(asn_DEF_ExtendedAliasAddress_tags_1)
		/sizeof(asn_DEF_ExtendedAliasAddress_tags_1[0]), /* 1 */
	asn_DEF_ExtendedAliasAddress_tags_1,	/* Same as above */
	sizeof(asn_DEF_ExtendedAliasAddress_tags_1)
		/sizeof(asn_DEF_ExtendedAliasAddress_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ExtendedAliasAddress_1,
	3,	/* Elements count */
	&asn_SPC_ExtendedAliasAddress_specs_1	/* Additional specs */
};

