/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_FeatureDescriptor_H_
#define	_FeatureDescriptor_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GenericIdentifier.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EnumeratedParameter;

/* FeatureDescriptor */
typedef struct FeatureDescriptor {
	GenericIdentifier_t	 id;
	struct FeatureDescriptor__parameters {
		A_SEQUENCE_OF(struct EnumeratedParameter) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *parameters;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FeatureDescriptor_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FeatureDescriptor;
extern asn_SEQUENCE_specifics_t asn_SPC_FeatureDescriptor_specs_1;
extern asn_TYPE_member_t asn_MBR_FeatureDescriptor_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EnumeratedParameter.h"

#endif	/* _FeatureDescriptor_H_ */
#include <asn_internal.h>
