/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#include "FeatureDescriptor.h"

static asn_TYPE_member_t asn_MBR_parameters_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EnumeratedParameter,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_parameters_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_parameters_specs_3 = {
	sizeof(struct FeatureDescriptor__parameters),
	offsetof(struct FeatureDescriptor__parameters, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_parameters_3 = {
	"parameters",
	"parameters",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_parameters_tags_3,
	sizeof(asn_DEF_parameters_tags_3)
		/sizeof(asn_DEF_parameters_tags_3[0]) - 1, /* 1 */
	asn_DEF_parameters_tags_3,	/* Same as above */
	sizeof(asn_DEF_parameters_tags_3)
		/sizeof(asn_DEF_parameters_tags_3[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_parameters_3,
	1,	/* Single element */
	&asn_SPC_parameters_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_FeatureDescriptor_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FeatureDescriptor, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GenericIdentifier,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"id"
		},
	{ ATF_POINTER, 1, offsetof(struct FeatureDescriptor, parameters),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_parameters_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"parameters"
		},
};
static const int asn_MAP_FeatureDescriptor_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_FeatureDescriptor_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FeatureDescriptor_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* parameters */
};
asn_SEQUENCE_specifics_t asn_SPC_FeatureDescriptor_specs_1 = {
	sizeof(struct FeatureDescriptor),
	offsetof(struct FeatureDescriptor, _asn_ctx),
	asn_MAP_FeatureDescriptor_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_FeatureDescriptor_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_FeatureDescriptor = {
	"FeatureDescriptor",
	"FeatureDescriptor",
	&asn_OP_SEQUENCE,
	asn_DEF_FeatureDescriptor_tags_1,
	sizeof(asn_DEF_FeatureDescriptor_tags_1)
		/sizeof(asn_DEF_FeatureDescriptor_tags_1[0]), /* 1 */
	asn_DEF_FeatureDescriptor_tags_1,	/* Same as above */
	sizeof(asn_DEF_FeatureDescriptor_tags_1)
		/sizeof(asn_DEF_FeatureDescriptor_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_FeatureDescriptor_1,
	2,	/* Elements count */
	&asn_SPC_FeatureDescriptor_specs_1	/* Additional specs */
};

