/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_GenericIdentifier_H_
#define	_GenericIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OBJECT_IDENTIFIER.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GenericIdentifier_PR {
	GenericIdentifier_PR_NOTHING,	/* No components present */
	GenericIdentifier_PR_standard,
	GenericIdentifier_PR_oid
	/* Extensions may appear below */
	
} GenericIdentifier_PR;

/* GenericIdentifier */
typedef struct GenericIdentifier {
	GenericIdentifier_PR present;
	union GenericIdentifier_u {
		long	 standard;
		OBJECT_IDENTIFIER_t	 oid;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GenericIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GenericIdentifier;
extern asn_CHOICE_specifics_t asn_SPC_GenericIdentifier_specs_1;
extern asn_TYPE_member_t asn_MBR_GenericIdentifier_1[2];
extern asn_per_constraints_t asn_PER_type_GenericIdentifier_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _GenericIdentifier_H_ */
#include <asn_internal.h>
