/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_H221NonStandard_H_
#define	_H221NonStandard_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* H221NonStandard */
typedef struct H221NonStandard {
	long	 t35CountryCode;
	long	 t35Extension;
	long	 manufacturerCode;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} H221NonStandard_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_H221NonStandard;
extern asn_SEQUENCE_specifics_t asn_SPC_H221NonStandard_specs_1;
extern asn_TYPE_member_t asn_MBR_H221NonStandard_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _H221NonStandard_H_ */
#include <asn_internal.h>
