/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_H320Caps_H_
#define	_H320Caps_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NonStandardParameter;

/* H320Caps */
typedef struct H320Caps {
	struct NonStandardParameter	*nonStandardData;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} H320Caps_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_H320Caps;
extern asn_SEQUENCE_specifics_t asn_SPC_H320Caps_specs_1;
extern asn_TYPE_member_t asn_MBR_H320Caps_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NonStandardParameter.h"

#endif	/* _H320Caps_H_ */
#include <asn_internal.h>
