/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#include "H323-UserInformation.h"

static asn_TYPE_member_t asn_MBR_H323_UserInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct H323_UserInformation, h323_uu_pdu),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_H323_UU_PDU,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"h323-uu-pdu"
		},
	{ ATF_POINTER, 1, offsetof(struct H323_UserInformation, user_data),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"user-data"
		},
};
static const int asn_MAP_H323_UserInformation_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_H323_UserInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_H323_UserInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* h323-uu-pdu */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* user-data */
};
static asn_SEQUENCE_specifics_t asn_SPC_H323_UserInformation_specs_1 = {
	sizeof(struct H323_UserInformation),
	offsetof(struct H323_UserInformation, _asn_ctx),
	asn_MAP_H323_UserInformation_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_H323_UserInformation_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_H323_UserInformation = {
	"H323-UserInformation",
	"H323-UserInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_H323_UserInformation_tags_1,
	sizeof(asn_DEF_H323_UserInformation_tags_1)
		/sizeof(asn_DEF_H323_UserInformation_tags_1[0]), /* 1 */
	asn_DEF_H323_UserInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_H323_UserInformation_tags_1)
		/sizeof(asn_DEF_H323_UserInformation_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_H323_UserInformation_1,
	2,	/* Elements count */
	&asn_SPC_H323_UserInformation_specs_1	/* Additional specs */
};

