/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_H323_UserInformation_H_
#define	_H323_UserInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "H323-UU-PDU.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* H323-UserInformation */
typedef struct H323_UserInformation {
	H323_UU_PDU_t	 h323_uu_pdu;
	OCTET_STRING_t	*user_data;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} H323_UserInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_H323_UserInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _H323_UserInformation_H_ */
#include <asn_internal.h>
