/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#include "NestedcryptoToken.h"

asn_TYPE_member_t asn_MBR_NestedcryptoToken_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NestedcryptoToken, tokenOID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"tokenOID"
		},
	{ ATF_POINTER, 0, offsetof(struct NestedcryptoToken, cryptoToken),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CryptoH323Token,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"cryptoToken"
		},
};
static const ber_tlv_tag_t asn_DEF_NestedcryptoToken_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NestedcryptoToken_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* tokenOID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cryptoToken */
};
asn_SEQUENCE_specifics_t asn_SPC_NestedcryptoToken_specs_1 = {
	sizeof(struct NestedcryptoToken),
	offsetof(struct NestedcryptoToken, _asn_ctx),
	asn_MAP_NestedcryptoToken_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NestedcryptoToken = {
	"NestedcryptoToken",
	"NestedcryptoToken",
	&asn_OP_SEQUENCE,
	asn_DEF_NestedcryptoToken_tags_1,
	sizeof(asn_DEF_NestedcryptoToken_tags_1)
		/sizeof(asn_DEF_NestedcryptoToken_tags_1[0]), /* 1 */
	asn_DEF_NestedcryptoToken_tags_1,	/* Same as above */
	sizeof(asn_DEF_NestedcryptoToken_tags_1)
		/sizeof(asn_DEF_NestedcryptoToken_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_NestedcryptoToken_1,
	2,	/* Elements count */
	&asn_SPC_NestedcryptoToken_specs_1	/* Additional specs */
};

