/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_NonStandardIdentifier_H_
#define	_NonStandardIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NonStandardIdentifier_PR {
	NonStandardIdentifier_PR_NOTHING,	/* No components present */
	NonStandardIdentifier_PR_object,
	NonStandardIdentifier_PR_h221NonStandard
} NonStandardIdentifier_PR;

/* NonStandardIdentifier */
typedef struct NonStandardIdentifier {
	NonStandardIdentifier_PR present;
	union NonStandardIdentifier_u {
		OBJECT_IDENTIFIER_t	 object;
		struct NonStandardIdentifier__h221NonStandard {
			long	 t35CountryCode;
			long	 t35Extension;
			long	 manufacturerCode;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} h221NonStandard;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NonStandardIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NonStandardIdentifier;
extern asn_CHOICE_specifics_t asn_SPC_NonStandardIdentifier_specs_1;
extern asn_TYPE_member_t asn_MBR_NonStandardIdentifier_1[2];
extern asn_per_constraints_t asn_PER_type_NonStandardIdentifier_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NonStandardIdentifier_H_ */
#include <asn_internal.h>
