/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_NonStandardParameter_H_
#define	_NonStandardParameter_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NonStandardIdentifier.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NonStandardParameter */
typedef struct NonStandardParameter {
	NonStandardIdentifier_t	 nonStandardIdentifier;
	OCTET_STRING_t	 data;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NonStandardParameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NonStandardParameter;
extern asn_SEQUENCE_specifics_t asn_SPC_NonStandardParameter_specs_1;
extern asn_TYPE_member_t asn_MBR_NonStandardParameter_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _NonStandardParameter_H_ */
#include <asn_internal.h>
