/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_ParameterIdentifier_H_
#define	_ParameterIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OBJECT_IDENTIFIER.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ParameterIdentifier_PR {
	ParameterIdentifier_PR_NOTHING,	/* No components present */
	ParameterIdentifier_PR_standard,
	ParameterIdentifier_PR_oid
	/* Extensions may appear below */
	
} ParameterIdentifier_PR;

/* ParameterIdentifier */
typedef struct ParameterIdentifier {
	ParameterIdentifier_PR present;
	union ParameterIdentifier_u {
		long	 standard;
		OBJECT_IDENTIFIER_t	 oid;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ParameterIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParameterIdentifier;
extern asn_CHOICE_specifics_t asn_SPC_ParameterIdentifier_specs_1;
extern asn_TYPE_member_t asn_MBR_ParameterIdentifier_1[2];
extern asn_per_constraints_t asn_PER_type_ParameterIdentifier_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ParameterIdentifier_H_ */
#include <asn_internal.h>
