/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_Params_H_
#define	_Params_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Params */
typedef struct Params {
	long	*ranInt;	/* OPTIONAL */
	OCTET_STRING_t	*iv;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Params_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Params;
extern asn_SEQUENCE_specifics_t asn_SPC_Params_specs_1;
extern asn_TYPE_member_t asn_MBR_Params_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Params_H_ */
#include <asn_internal.h>
