/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_PartyNumber_H_
#define	_PartyNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PublicPartyNumber.h"
#include "DataPartyNumber.h"
#include "TelexPartyNumber.h"
#include "PrivatePartyNumber.h"
#include "NationalStandardPartyNumber.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PartyNumber_PR {
	PartyNumber_PR_NOTHING,	/* No components present */
	PartyNumber_PR_publicPartyNumber,
	PartyNumber_PR_dataPartyNumber,
	PartyNumber_PR_telexPartyNumber,
	PartyNumber_PR_privatePartyNumber,
	PartyNumber_PR_nationalStandardPartyNumber
	/* Extensions may appear below */
	
} PartyNumber_PR;

/* PartyNumber */
typedef struct PartyNumber {
	PartyNumber_PR present;
	union PartyNumber_u {
		PublicPartyNumber_t	 publicPartyNumber;
		DataPartyNumber_t	 dataPartyNumber;
		TelexPartyNumber_t	 telexPartyNumber;
		PrivatePartyNumber_t	 privatePartyNumber;
		NationalStandardPartyNumber_t	 nationalStandardPartyNumber;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PartyNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PartyNumber;
extern asn_CHOICE_specifics_t asn_SPC_PartyNumber_specs_1;
extern asn_TYPE_member_t asn_MBR_PartyNumber_1[5];
extern asn_per_constraints_t asn_PER_type_PartyNumber_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PartyNumber_H_ */
#include <asn_internal.h>
