/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_Password_H_
#define	_Password_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BMPString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Password */
typedef BMPString_t	 Password_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Password_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Password;
asn_struct_free_f Password_free;
asn_struct_print_f Password_print;
asn_constr_check_f Password_constraint;
ber_type_decoder_f Password_decode_ber;
der_type_encoder_f Password_encode_der;
xer_type_decoder_f Password_decode_xer;
xer_type_encoder_f Password_encode_xer;
jer_type_encoder_f Password_encode_jer;
oer_type_decoder_f Password_decode_oer;
oer_type_encoder_f Password_encode_oer;
per_type_decoder_f Password_decode_uper;
per_type_encoder_f Password_encode_uper;
per_type_decoder_f Password_decode_aper;
per_type_encoder_f Password_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Password_H_ */
#include <asn_internal.h>
