/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_CallModel;
extern struct asn_TYPE_descriptor_s asn_DEF_H323_UserInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module H323-MESSAGES in h323-messages.asn */
	&asn_DEF_CallModel,	
	&asn_DEF_H323_UserInformation,	
	/* From module ASN1C-UsefulInformationObjectClasses in ./asn1c/../skeletons/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_EXTERNAL,	
	0
};

