/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_PresentationIndicator_H_
#define	_PresentationIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PresentationIndicator {
	PresentationIndicator_presentationAllowed	= 0,
	PresentationIndicator_presentationRestricted	= 1,
	PresentationIndicator_addressNotAvailable	= 2
	/*
	 * Enumeration is extensible
	 */
} e_PresentationIndicator;

/* PresentationIndicator */
typedef long	 PresentationIndicator_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PresentationIndicator_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PresentationIndicator;
extern const asn_INTEGER_specifics_t asn_SPC_PresentationIndicator_specs_1;
asn_struct_free_f PresentationIndicator_free;
asn_struct_print_f PresentationIndicator_print;
asn_constr_check_f PresentationIndicator_constraint;
ber_type_decoder_f PresentationIndicator_decode_ber;
der_type_encoder_f PresentationIndicator_encode_der;
xer_type_decoder_f PresentationIndicator_decode_xer;
xer_type_encoder_f PresentationIndicator_encode_xer;
jer_type_encoder_f PresentationIndicator_encode_jer;
oer_type_decoder_f PresentationIndicator_decode_oer;
oer_type_encoder_f PresentationIndicator_encode_oer;
per_type_decoder_f PresentationIndicator_decode_uper;
per_type_encoder_f PresentationIndicator_encode_uper;
per_type_decoder_f PresentationIndicator_decode_aper;
per_type_encoder_f PresentationIndicator_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PresentationIndicator_H_ */
#include <asn_internal.h>
