/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_PrivateTypeOfNumber_H_
#define	_PrivateTypeOfNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PrivateTypeOfNumber {
	PrivateTypeOfNumber_unknown	= 0,
	PrivateTypeOfNumber_level2RegionalNumber	= 1,
	PrivateTypeOfNumber_level1RegionalNumber	= 2,
	PrivateTypeOfNumber_pISNSpecificNumber	= 3,
	PrivateTypeOfNumber_localNumber	= 4,
	PrivateTypeOfNumber_abbreviatedNumber	= 6
	/*
	 * Enumeration is extensible
	 */
} e_PrivateTypeOfNumber;

/* PrivateTypeOfNumber */
typedef long	 PrivateTypeOfNumber_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PrivateTypeOfNumber_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PrivateTypeOfNumber;
extern const asn_INTEGER_specifics_t asn_SPC_PrivateTypeOfNumber_specs_1;
asn_struct_free_f PrivateTypeOfNumber_free;
asn_struct_print_f PrivateTypeOfNumber_print;
asn_constr_check_f PrivateTypeOfNumber_constraint;
ber_type_decoder_f PrivateTypeOfNumber_decode_ber;
der_type_encoder_f PrivateTypeOfNumber_encode_der;
xer_type_decoder_f PrivateTypeOfNumber_decode_xer;
xer_type_encoder_f PrivateTypeOfNumber_encode_xer;
jer_type_encoder_f PrivateTypeOfNumber_encode_jer;
oer_type_decoder_f PrivateTypeOfNumber_decode_oer;
oer_type_encoder_f PrivateTypeOfNumber_encode_oer;
per_type_decoder_f PrivateTypeOfNumber_decode_uper;
per_type_encoder_f PrivateTypeOfNumber_encode_uper;
per_type_decoder_f PrivateTypeOfNumber_decode_aper;
per_type_encoder_f PrivateTypeOfNumber_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PrivateTypeOfNumber_H_ */
#include <asn_internal.h>
