/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_ProtocolIdentifier_H_
#define	_ProtocolIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProtocolIdentifier */
typedef OBJECT_IDENTIFIER_t	 ProtocolIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIdentifier;
asn_struct_free_f ProtocolIdentifier_free;
asn_struct_print_f ProtocolIdentifier_print;
asn_constr_check_f ProtocolIdentifier_constraint;
ber_type_decoder_f ProtocolIdentifier_decode_ber;
der_type_encoder_f ProtocolIdentifier_encode_der;
xer_type_decoder_f ProtocolIdentifier_decode_xer;
xer_type_encoder_f ProtocolIdentifier_encode_xer;
jer_type_encoder_f ProtocolIdentifier_encode_jer;
oer_type_decoder_f ProtocolIdentifier_decode_oer;
oer_type_encoder_f ProtocolIdentifier_encode_oer;
per_type_decoder_f ProtocolIdentifier_decode_uper;
per_type_encoder_f ProtocolIdentifier_encode_uper;
per_type_decoder_f ProtocolIdentifier_decode_aper;
per_type_encoder_f ProtocolIdentifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIdentifier_H_ */
#include <asn_internal.h>
