/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#include "ProtocolIdentifier.h"

/*
 * This type is implemented using OBJECT_IDENTIFIER,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_ProtocolIdentifier_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (6 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIdentifier = {
	"ProtocolIdentifier",
	"ProtocolIdentifier",
	&asn_OP_OBJECT_IDENTIFIER,
	asn_DEF_ProtocolIdentifier_tags_1,
	sizeof(asn_DEF_ProtocolIdentifier_tags_1)
		/sizeof(asn_DEF_ProtocolIdentifier_tags_1[0]), /* 1 */
	asn_DEF_ProtocolIdentifier_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtocolIdentifier_tags_1)
		/sizeof(asn_DEF_ProtocolIdentifier_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		OBJECT_IDENTIFIER_constraint
	},
	0, 0,	/* No members */
	0	/* No specifics */
};

