/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_PublicPartyNumber_H_
#define	_PublicPartyNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PublicTypeOfNumber.h"
#include "NumberDigits.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PublicPartyNumber */
typedef struct PublicPartyNumber {
	PublicTypeOfNumber_t	 publicTypeOfNumber;
	NumberDigits_t	 publicNumberDigits;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PublicPartyNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PublicPartyNumber;
extern asn_SEQUENCE_specifics_t asn_SPC_PublicPartyNumber_specs_1;
extern asn_TYPE_member_t asn_MBR_PublicPartyNumber_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PublicPartyNumber_H_ */
#include <asn_internal.h>
