/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_PublicTypeOfNumber_H_
#define	_PublicTypeOfNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PublicTypeOfNumber {
	PublicTypeOfNumber_unknown	= 0,
	PublicTypeOfNumber_internationalNumber	= 1,
	PublicTypeOfNumber_nationalNumber	= 2,
	PublicTypeOfNumber_networkSpecificNumber	= 3,
	PublicTypeOfNumber_subscriberNumber	= 4,
	PublicTypeOfNumber_abbreviatedNumber	= 6
	/*
	 * Enumeration is extensible
	 */
} e_PublicTypeOfNumber;

/* PublicTypeOfNumber */
typedef long	 PublicTypeOfNumber_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PublicTypeOfNumber_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PublicTypeOfNumber;
extern const asn_INTEGER_specifics_t asn_SPC_PublicTypeOfNumber_specs_1;
asn_struct_free_f PublicTypeOfNumber_free;
asn_struct_print_f PublicTypeOfNumber_print;
asn_constr_check_f PublicTypeOfNumber_constraint;
ber_type_decoder_f PublicTypeOfNumber_decode_ber;
der_type_encoder_f PublicTypeOfNumber_encode_der;
xer_type_decoder_f PublicTypeOfNumber_decode_xer;
xer_type_encoder_f PublicTypeOfNumber_encode_xer;
jer_type_encoder_f PublicTypeOfNumber_encode_jer;
oer_type_decoder_f PublicTypeOfNumber_decode_oer;
oer_type_encoder_f PublicTypeOfNumber_encode_oer;
per_type_decoder_f PublicTypeOfNumber_decode_uper;
per_type_encoder_f PublicTypeOfNumber_encode_uper;
per_type_decoder_f PublicTypeOfNumber_decode_aper;
per_type_encoder_f PublicTypeOfNumber_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PublicTypeOfNumber_H_ */
#include <asn_internal.h>
