/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_QOSCapability_H_
#define	_QOSCapability_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NonStandardParameter.h"
#include "RSVPParameters.h"
#include "ATMParameters.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum QOSCapability_PR {
	QOSCapability_PR_NOTHING,	/* No components present */
	QOSCapability_PR_nonStandardData,
	QOSCapability_PR_rsvpParameters,
	QOSCapability_PR_atmParameters
	/* Extensions may appear below */
	
} QOSCapability_PR;

/* QOSCapability */
typedef struct QOSCapability {
	QOSCapability_PR present;
	union QOSCapability_u {
		NonStandardParameter_t	 nonStandardData;
		RSVPParameters_t	 rsvpParameters;
		ATMParameters_t	 atmParameters;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} QOSCapability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QOSCapability;
extern asn_CHOICE_specifics_t asn_SPC_QOSCapability_specs_1;
extern asn_TYPE_member_t asn_MBR_QOSCapability_1[3];
extern asn_per_constraints_t asn_PER_type_QOSCapability_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _QOSCapability_H_ */
#include <asn_internal.h>
