/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#include "QOSCapabilities.h"

asn_TYPE_member_t asn_MBR_QOSCapabilities_1[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_QOSCapability,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_QOSCapabilities_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_QOSCapabilities_specs_1 = {
	sizeof(struct QOSCapabilities),
	offsetof(struct QOSCapabilities, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
asn_TYPE_descriptor_t asn_DEF_QOSCapabilities = {
	"QOSCapabilities",
	"QOSCapabilities",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_QOSCapabilities_tags_1,
	sizeof(asn_DEF_QOSCapabilities_tags_1)
		/sizeof(asn_DEF_QOSCapabilities_tags_1[0]), /* 1 */
	asn_DEF_QOSCapabilities_tags_1,	/* Same as above */
	sizeof(asn_DEF_QOSCapabilities_tags_1)
		/sizeof(asn_DEF_QOSCapabilities_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_QOSCapabilities_1,
	1,	/* Single element */
	&asn_SPC_QOSCapabilities_specs_1	/* Additional specs */
};

