/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_QOSMode_H_
#define	_QOSMode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum QOSMode {
	QOSMode_guaranteedQOS	= 0,
	QOSMode_controlledLoad	= 1
	/*
	 * Enumeration is extensible
	 */
} e_QOSMode;

/* QOSMode */
typedef long	 QOSMode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_QOSMode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_QOSMode;
extern const asn_INTEGER_specifics_t asn_SPC_QOSMode_specs_1;
asn_struct_free_f QOSMode_free;
asn_struct_print_f QOSMode_print;
asn_constr_check_f QOSMode_constraint;
ber_type_decoder_f QOSMode_decode_ber;
der_type_encoder_f QOSMode_encode_der;
xer_type_decoder_f QOSMode_decode_xer;
xer_type_encoder_f QOSMode_encode_xer;
jer_type_encoder_f QOSMode_encode_jer;
oer_type_decoder_f QOSMode_decode_oer;
oer_type_encoder_f QOSMode_encode_oer;
per_type_decoder_f QOSMode_decode_uper;
per_type_encoder_f QOSMode_encode_uper;
per_type_decoder_f QOSMode_decode_aper;
per_type_encoder_f QOSMode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _QOSMode_H_ */
#include <asn_internal.h>
