/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_RandomVal_H_
#define	_RandomVal_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RandomVal */
typedef long	 RandomVal_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RandomVal;
asn_struct_free_f RandomVal_free;
asn_struct_print_f RandomVal_print;
asn_constr_check_f RandomVal_constraint;
ber_type_decoder_f RandomVal_decode_ber;
der_type_encoder_f RandomVal_encode_der;
xer_type_decoder_f RandomVal_decode_xer;
xer_type_encoder_f RandomVal_encode_xer;
jer_type_encoder_f RandomVal_encode_jer;
oer_type_decoder_f RandomVal_decode_oer;
oer_type_encoder_f RandomVal_encode_oer;
per_type_decoder_f RandomVal_decode_uper;
per_type_encoder_f RandomVal_encode_uper;
per_type_decoder_f RandomVal_decode_aper;
per_type_encoder_f RandomVal_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RandomVal_H_ */
#include <asn_internal.h>
