/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_ReleaseComplete_UUIE_H_
#define	_ReleaseComplete_UUIE_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIdentifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReleaseComplete-UUIE */
typedef struct ReleaseComplete_UUIE {
	ProtocolIdentifier_t	 protocolIdentifier;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReleaseComplete_UUIE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReleaseComplete_UUIE;
extern asn_SEQUENCE_specifics_t asn_SPC_ReleaseComplete_UUIE_specs_1;
extern asn_TYPE_member_t asn_MBR_ReleaseComplete_UUIE_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _ReleaseComplete_UUIE_H_ */
#include <asn_internal.h>
