/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_RSVPParameters_H_
#define	_RSVPParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include "QOSMode.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RSVPParameters */
typedef struct RSVPParameters {
	QOSMode_t	 qosMode;
	unsigned long	*tokenRate;	/* OPTIONAL */
	unsigned long	*bucketSize;	/* OPTIONAL */
	unsigned long	*peakRate;	/* OPTIONAL */
	unsigned long	*minPoliced;	/* OPTIONAL */
	unsigned long	*maxPktSize;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RSVPParameters_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_tokenRate_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_bucketSize_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_peakRate_5;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_minPoliced_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_maxPktSize_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RSVPParameters;
extern asn_SEQUENCE_specifics_t asn_SPC_RSVPParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_RSVPParameters_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _RSVPParameters_H_ */
#include <asn_internal.h>
