/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_SecurityCapabilities_H_
#define	_SecurityCapabilities_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NonStandardParameter;
struct EncryptionCapability;
struct CertificateCapability;

/* SecurityCapabilities */
typedef struct SecurityCapabilities {
	struct NonStandardParameter	*nonStandard;	/* OPTIONAL */
	struct EncryptionCapability	*encryption;	/* OPTIONAL */
	BOOLEAN_t	 authenticatedSupplier;
	BOOLEAN_t	 authenticatedSignalling;
	struct CertificateCapability	*certificateCapability;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecurityCapabilities_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityCapabilities;
extern asn_SEQUENCE_specifics_t asn_SPC_SecurityCapabilities_specs_1;
extern asn_TYPE_member_t asn_MBR_SecurityCapabilities_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NonStandardParameter.h"
#include "EncryptionCapability.h"
#include "CertificateCapability.h"

#endif	/* _SecurityCapabilities_H_ */
#include <asn_internal.h>
