/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_ServiceControlSession_H_
#define	_ServiceControlSession_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "ServiceControlSession-reason.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Contents;

/* ServiceControlSession */
typedef struct ServiceControlSession {
	long	 sessionId;
	struct Contents	*contents;	/* OPTIONAL */
	ServiceControlSession_reason_t	*reason;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServiceControlSession_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceControlSession;
extern asn_SEQUENCE_specifics_t asn_SPC_ServiceControlSession_specs_1;
extern asn_TYPE_member_t asn_MBR_ServiceControlSession_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Contents.h"

#endif	/* _ServiceControlSession_H_ */
#include <asn_internal.h>
