/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_ServiceControlSession_reason_H_
#define	_ServiceControlSession_reason_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServiceControlSession_reason {
	ServiceControlSession_reason_open	= 1,
	ServiceControlSession_reason_refresh	= 2,
	ServiceControlSession_reason_close	= 3
	/*
	 * Enumeration is extensible
	 */
} e_ServiceControlSession_reason;

/* ServiceControlSession-reason */
typedef long	 ServiceControlSession_reason_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ServiceControlSession_reason_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ServiceControlSession_reason;
extern const asn_INTEGER_specifics_t asn_SPC_ServiceControlSession_reason_specs_1;
asn_struct_free_f ServiceControlSession_reason_free;
asn_struct_print_f ServiceControlSession_reason_print;
asn_constr_check_f ServiceControlSession_reason_constraint;
ber_type_decoder_f ServiceControlSession_reason_decode_ber;
der_type_encoder_f ServiceControlSession_reason_encode_der;
xer_type_decoder_f ServiceControlSession_reason_decode_xer;
xer_type_encoder_f ServiceControlSession_reason_encode_xer;
jer_type_encoder_f ServiceControlSession_reason_encode_jer;
oer_type_decoder_f ServiceControlSession_reason_decode_oer;
oer_type_encoder_f ServiceControlSession_reason_encode_oer;
per_type_decoder_f ServiceControlSession_reason_decode_uper;
per_type_encoder_f ServiceControlSession_reason_encode_uper;
per_type_decoder_f ServiceControlSession_reason_decode_aper;
per_type_encoder_f ServiceControlSession_reason_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceControlSession_reason_H_ */
#include <asn_internal.h>
