/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#include "StatusInquiry-UUIE.h"

asn_TYPE_member_t asn_MBR_StatusInquiry_UUIE_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct StatusInquiry_UUIE, protocolIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolIdentifier,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"protocolIdentifier"
		},
};
static const ber_tlv_tag_t asn_DEF_StatusInquiry_UUIE_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_StatusInquiry_UUIE_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* protocolIdentifier */
};
asn_SEQUENCE_specifics_t asn_SPC_StatusInquiry_UUIE_specs_1 = {
	sizeof(struct StatusInquiry_UUIE),
	offsetof(struct StatusInquiry_UUIE, _asn_ctx),
	asn_MAP_StatusInquiry_UUIE_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_StatusInquiry_UUIE = {
	"StatusInquiry-UUIE",
	"StatusInquiry-UUIE",
	&asn_OP_SEQUENCE,
	asn_DEF_StatusInquiry_UUIE_tags_1,
	sizeof(asn_DEF_StatusInquiry_UUIE_tags_1)
		/sizeof(asn_DEF_StatusInquiry_UUIE_tags_1[0]), /* 1 */
	asn_DEF_StatusInquiry_UUIE_tags_1,	/* Same as above */
	sizeof(asn_DEF_StatusInquiry_UUIE_tags_1)
		/sizeof(asn_DEF_StatusInquiry_UUIE_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_StatusInquiry_UUIE_1,
	1,	/* Elements count */
	&asn_SPC_StatusInquiry_UUIE_specs_1	/* Additional specs */
};

