/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_SupportedProtocols_H_
#define	_SupportedProtocols_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NonStandardParameter.h"
#include "H310Caps.h"
#include "H320Caps.h"
#include "H321Caps.h"
#include "H322Caps.h"
#include "H323Caps.h"
#include "H324Caps.h"
#include "VoiceCaps.h"
#include "T120OnlyCaps.h"
#include "NonStandardProtocol.h"
#include "T38FaxAnnexbOnlyCaps.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SupportedProtocols_PR {
	SupportedProtocols_PR_NOTHING,	/* No components present */
	SupportedProtocols_PR_nonStandardData,
	SupportedProtocols_PR_h310,
	SupportedProtocols_PR_h320,
	SupportedProtocols_PR_h321,
	SupportedProtocols_PR_h322,
	SupportedProtocols_PR_h323,
	SupportedProtocols_PR_h324,
	SupportedProtocols_PR_voice,
	SupportedProtocols_PR_t120_only,
	SupportedProtocols_PR_nonStandardProtocol,
	SupportedProtocols_PR_t38FaxAnnexbOnly
	/* Extensions may appear below */
	
} SupportedProtocols_PR;

/* SupportedProtocols */
typedef struct SupportedProtocols {
	SupportedProtocols_PR present;
	union SupportedProtocols_u {
		NonStandardParameter_t	 nonStandardData;
		H310Caps_t	 h310;
		H320Caps_t	 h320;
		H321Caps_t	 h321;
		H322Caps_t	 h322;
		H323Caps_t	 h323;
		H324Caps_t	 h324;
		VoiceCaps_t	 voice;
		T120OnlyCaps_t	 t120_only;
		NonStandardProtocol_t	 nonStandardProtocol;
		T38FaxAnnexbOnlyCaps_t	 t38FaxAnnexbOnly;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SupportedProtocols_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SupportedProtocols;
extern asn_CHOICE_specifics_t asn_SPC_SupportedProtocols_specs_1;
extern asn_TYPE_member_t asn_MBR_SupportedProtocols_1[11];
extern asn_per_constraints_t asn_PER_type_SupportedProtocols_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SupportedProtocols_H_ */
#include <asn_internal.h>
