/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#include "T120OnlyCaps.h"

asn_TYPE_member_t asn_MBR_T120OnlyCaps_1[] = {
	{ ATF_POINTER, 1, offsetof(struct T120OnlyCaps, nonStandardData),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NonStandardParameter,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nonStandardData"
		},
};
static const int asn_MAP_T120OnlyCaps_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_T120OnlyCaps_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_T120OnlyCaps_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* nonStandardData */
};
asn_SEQUENCE_specifics_t asn_SPC_T120OnlyCaps_specs_1 = {
	sizeof(struct T120OnlyCaps),
	offsetof(struct T120OnlyCaps, _asn_ctx),
	asn_MAP_T120OnlyCaps_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_T120OnlyCaps_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_T120OnlyCaps = {
	"T120OnlyCaps",
	"T120OnlyCaps",
	&asn_OP_SEQUENCE,
	asn_DEF_T120OnlyCaps_tags_1,
	sizeof(asn_DEF_T120OnlyCaps_tags_1)
		/sizeof(asn_DEF_T120OnlyCaps_tags_1[0]), /* 1 */
	asn_DEF_T120OnlyCaps_tags_1,	/* Same as above */
	sizeof(asn_DEF_T120OnlyCaps_tags_1)
		/sizeof(asn_DEF_T120OnlyCaps_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_T120OnlyCaps_1,
	1,	/* Elements count */
	&asn_SPC_T120OnlyCaps_specs_1	/* Additional specs */
};

