/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_TelexTypeOfNumber_H_
#define	_TelexTypeOfNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TelexTypeOfNumber {
	TelexTypeOfNumber_unknown	= 0,
	TelexTypeOfNumber_internationalNumber	= 1,
	TelexTypeOfNumber_nationalNumber	= 2,
	TelexTypeOfNumber_networkSpecificNumber	= 3,
	TelexTypeOfNumber_subscriberNumber	= 4,
	TelexTypeOfNumber_abbreviatedNumber	= 6
	/*
	 * Enumeration is extensible
	 */
} e_TelexTypeOfNumber;

/* TelexTypeOfNumber */
typedef long	 TelexTypeOfNumber_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TelexTypeOfNumber_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TelexTypeOfNumber;
extern const asn_INTEGER_specifics_t asn_SPC_TelexTypeOfNumber_specs_1;
asn_struct_free_f TelexTypeOfNumber_free;
asn_struct_print_f TelexTypeOfNumber_print;
asn_constr_check_f TelexTypeOfNumber_constraint;
ber_type_decoder_f TelexTypeOfNumber_decode_ber;
der_type_encoder_f TelexTypeOfNumber_encode_der;
xer_type_decoder_f TelexTypeOfNumber_decode_xer;
xer_type_encoder_f TelexTypeOfNumber_encode_xer;
jer_type_encoder_f TelexTypeOfNumber_encode_jer;
oer_type_decoder_f TelexTypeOfNumber_decode_oer;
oer_type_encoder_f TelexTypeOfNumber_encode_oer;
per_type_decoder_f TelexTypeOfNumber_decode_uper;
per_type_encoder_f TelexTypeOfNumber_encode_uper;
per_type_decoder_f TelexTypeOfNumber_decode_aper;
per_type_encoder_f TelexTypeOfNumber_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TelexTypeOfNumber_H_ */
#include <asn_internal.h>
