/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_TelexPartyNumber_H_
#define	_TelexPartyNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TelexTypeOfNumber.h"
#include "NumberDigits.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TelexPartyNumber */
typedef struct TelexPartyNumber {
	TelexTypeOfNumber_t	 telexTypeOfNumber;
	NumberDigits_t	 telexNumberDigits;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TelexPartyNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TelexPartyNumber;
extern asn_SEQUENCE_specifics_t asn_SPC_TelexPartyNumber_specs_1;
extern asn_TYPE_member_t asn_MBR_TelexPartyNumber_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TelexPartyNumber_H_ */
#include <asn_internal.h>
