/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_TransportAddress_H_
#define	_TransportAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TransportAddress_PR {
	TransportAddress_PR_NOTHING,	/* No components present */
	TransportAddress_PR_ipAddress,
	TransportAddress_PR_ipv6Address
	/* Extensions may appear below */
	
} TransportAddress_PR;

/* TransportAddress */
typedef struct TransportAddress {
	TransportAddress_PR present;
	union TransportAddress_u {
		struct TransportAddress__ipAddress {
			OCTET_STRING_t	 ip;
			long	 port;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ipAddress;
		struct TransportAddress__ipv6Address {
			OCTET_STRING_t	 ip;
			long	 port;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ipv6Address;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TransportAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransportAddress;
extern asn_CHOICE_specifics_t asn_SPC_TransportAddress_specs_1;
extern asn_TYPE_member_t asn_MBR_TransportAddress_1[2];
extern asn_per_constraints_t asn_PER_type_TransportAddress_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _TransportAddress_H_ */
#include <asn_internal.h>
