/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_TunnelledProtocol_H_
#define	_TunnelledProtocol_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TunnelledProtocol-id.h"
#include <IA5String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TunnelledProtocol */
typedef struct TunnelledProtocol {
	TunnelledProtocol_id_t	 id;
	IA5String_t	*subIdentifier;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TunnelledProtocol_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TunnelledProtocol;
extern asn_SEQUENCE_specifics_t asn_SPC_TunnelledProtocol_specs_1;
extern asn_TYPE_member_t asn_MBR_TunnelledProtocol_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TunnelledProtocol_H_ */
#include <asn_internal.h>
