/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_TunnelledSignallingMessage_H_
#define	_TunnelledSignallingMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TunnelledProtocol.h"
#include <NULL.h>
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NonStandardParameter;

/* TunnelledSignallingMessage */
typedef struct TunnelledSignallingMessage {
	TunnelledProtocol_t	 tunnelledProtocolID;
	struct TunnelledSignallingMessage__messageContent {
		A_SEQUENCE_OF(OCTET_STRING_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} messageContent;
	NULL_t	*tunnellingRequired;	/* OPTIONAL */
	struct NonStandardParameter	*nonStandardData;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TunnelledSignallingMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TunnelledSignallingMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_TunnelledSignallingMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_TunnelledSignallingMessage_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NonStandardParameter.h"

#endif	/* _TunnelledSignallingMessage_H_ */
#include <asn_internal.h>
