/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "H323-MESSAGES"
 * 	found in "h323-messages.asn"
 * 	`asn1c -fcompound-names -D h323_generated`
 */

#ifndef	_TypedCertificate_H_
#define	_TypedCertificate_H_


#include <asn_application.h>

/* Including external dependencies */
#include "X509Certificate.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TypedCertificate_PR {
	TypedCertificate_PR_NOTHING,	/* No components present */
	TypedCertificate_PR_x509Certificate
	/* Extensions may appear below */
	
} TypedCertificate_PR;

/* TypedCertificate */
typedef struct TypedCertificate {
	TypedCertificate_PR present;
	union TypedCertificate_u {
		X509Certificate_t	 x509Certificate;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TypedCertificate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TypedCertificate;
extern asn_CHOICE_specifics_t asn_SPC_TypedCertificate_specs_1;
extern asn_TYPE_member_t asn_MBR_TypedCertificate_1[1];
extern asn_per_constraints_t asn_PER_type_TypedCertificate_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _TypedCertificate_H_ */
#include <asn_internal.h>
