/*
 * Generated by asn1c-d143069-2025-12-02 (https://github.com/mouse07410/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_T;
extern struct asn_TYPE_descriptor_s asn_DEF_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module ModulePERLong in 134-per-long-OK.asn1 */
	&asn_DEF_T,	
	/* From module ASN1C-UsefulInformationObjectClasses in ../../skeletons/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_EXTERNAL,	
	0
};

