/*
 * Generated by asn1c-d143069-2025-12-02 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "ModulePERLong"
 * 	found in "134-per-long-OK.asn1"
 */

#ifndef	_T_H_
#define	_T_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* T */
typedef struct T {
	INTEGER_t	 unsigned33;
	INTEGER_t	 unsigned42;
	INTEGER_t	 signed33;
	INTEGER_t	 signed33ext;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} T_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_T;

#ifdef __cplusplus
}
#endif

#endif	/* _T_H_ */
#include <asn_internal.h>
